# Generated by Django 5.1 on 2024-08-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserBehavior', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='click',
            name='timestamp',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='keypress',
            name='timestamp',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='mousemove',
            name='timestamp',
            field=models.BigIntegerField(),
        ),
    ]
