# Generated by Django 5.1 on 2024-09-01 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserBehavior', '0003_alter_click_options_alter_keypress_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='click',
            table='UserBehavior_click',
        ),
        migrations.AlterModelTable(
            name='keypress',
            table='UserBehavior_keypress',
        ),
        migrations.AlterModelTable(
            name='mousemove',
            table='UserBehavior_mousemove',
        ),
    ]
